@echo off

echo The environements variables required by MESA have been emptied.
echo do not forget to Set your environement of work back before to use mesa.
echo Maya must to be restarted for the modifications to take effect.
echo ...
SETX SOURCE_BIN_PATH ""
echo SOURCE_BIN_PATH has been emptied.
echo ...
SETX GAME_PROJECT ""
echo GAME_PROJECT has been emptied.
echo ...
SETX GAME_PROJECT_SRC ""
echo GAME_PROJECT_SRC has been emptied.
echo ...
SETX GAME_PROJECT_NAME ""
echo GAME_PROJECT_NAME has been emptied.
echo ...
SETX XBMLANGPATH ""
echo XBMLANGPATH has been emptied.
echo ...
SETX MAYA_SCRIPT_PATH ""
echo MAYA_SCRIPT_PATH has been emptied.
echo ...
SETX MAYAVERSION ""
echo MAYAVERSION has been emptied.
echo ...
SETX STEAMDIR ""
echo STEAMDIR has been emptied.
echo ...
SETX STEAMUSER ""
echo STEAMUSER has been emptied.
echo ...
SETX MESADIR ""
echo MESADIR has been emptied.
echo ...
