//************************************************//
// Credits : ValVeSoftware, Prall, Nicolas Kirsch
// website http://puppetmaster.net ©2013
//************************************************//

// just a simple interface to the smdRead function with a file browser dialog

global proc string smdImport()
{
//source "smdRead.mel";
string $test = `fileDialog -dm "*.smd"`;
//return `smdreadani $test 1`;
return `smdRead $test 1`;
}